### ISSUE TITLE
`consensus_tests::sync_with_consensus` failed once

### ISSUE THREAD

**Issue by lxfind** [MystenLabs/sui#1096]
I observed this failure once, only once, not reproducible, could be some non-determinism in it.
```
thread 'consensus_client::consensus_tests::sync_with_consensus' panicked at 'called `Option::unwrap()` on a `None` value', /Users/xun/github/sui-upstream/test_utils/src/sequencer.rs:288:62
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   2: core::panicking::panic
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:48:5
   3: core::option::Option<T>::unwrap
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/option.rs:729:21
   4: test_utils::sequencer::SubscriberServer::synchronize::{{closure}}
             at /Users/xun/github/sui-upstream/test_utils/src/sequencer.rs:288:31
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/future/mod.rs:84:19
   6: <test_utils::sequencer::SubscriberServer as sui_network::transport::MessageHandler<Stream>>::handle_messages::{{closure}}
             at /Users/xun/github/sui-upstream/test_utils/src/sequencer.rs:331:96
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/future/mod.rs:84:19
   8: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/future/future.rs:123:9
   9: sui_network::transport::run_tcp_server::{{closure}}::{{closure}}
             at /Users/xun/github/sui-upstream/network_utils/src/transport.rs:212:50
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/future/mod.rs:84:19
  11: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /Users/xun/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/core.rs:161:17
  12: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/xun/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/loom/std/unsafe_cell.rs:14:9
  13: tokio::runtime::task::core::CoreStage<T>::poll
             at /Users/xun/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/core.rs:151:13
  14: tokio::runtime::task::harness::poll_future::{{closure}}
             at /Users/xun/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:467:19
  15: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panic/unwind_safe.rs:271:9
  16: std::panicking::try::do_call
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:406:40
  17: <unknown>
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:441:2
  18: std::panicking::try
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:370:19
  19: std::panic::catch_unwind
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panic.rs:133:14
  20: tokio::runtime::task::harness::poll_future
             at /Users/xun/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:455:18
  21: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /Users/xun/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:103:27
  22: tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/xun/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:57:15
  23: tokio::runtime::task::raw::poll
             at /Users/xun/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/raw.rs:128:5
  24: tokio::runtime::task::raw::RawTask::poll
             at /Users/xun/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/raw.rs:80:18
25: tokio::runtime::task::LocalNotified<S>::run
             at /Users/xun/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/mod.rs:347:9
  26: tokio::runtime::basic_scheduler::CoreGuard::block_on::{{closure}}::{{closure}}
             at /Users/xun/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:532:25
  27: tokio::coop::with_budget::{{closure}}
             at /Users/xun/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:102:9
  28: std::thread::local::LocalKey<T>::try_with
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/thread/local.rs:412:16
  29: std::thread::local::LocalKey<T>::with
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/thread/local.rs:388:9
  30: tokio::coop::with_budget
             at /Users/xun/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:95:5
  31: tokio::coop::budget
             at /Users/xun/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:72:5
  32: tokio::runtime::basic_scheduler::Context::run_task::{{closure}}
             at /Users/xun/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:291:29
  33: tokio::runtime::basic_scheduler::Context::enter
             at /Users/xun/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:356:19
  34: tokio::runtime::basic_scheduler::Context::run_task
             at /Users/xun/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:291:9
  35: tokio::runtime::basic_scheduler::CoreGuard::block_on::{{closure}}
             at /Users/xun/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:531:34
  36: tokio::runtime::basic_scheduler::CoreGuard::enter::{{closure}}
             at /Users/xun/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:555:57
  37: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /Users/xun/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/macros/scoped_tls.rs:61:9
  38: tokio::runtime::basic_scheduler::CoreGuard::enter
             at /Users/xun/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:555:27
  39: tokio::runtime::basic_scheduler::CoreGuard::block_on
             at /Users/xun/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:488:9
  40: tokio::runtime::basic_scheduler::BasicScheduler::block_on
             at /Users/xun/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:168:24
  41: tokio::runtime::Runtime::block_on
             at /Users/xun/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/mod.rs:475:46
  42: sui_core::consensus_client::consensus_tests::sync_with_consensus
             at ./src/unit_tests/consensus_tests.rs:266:5
  43: sui_core::consensus_client::consensus_tests::sync_with_consensus::{{closure}}
             at ./src/unit_tests/consensus_tests.rs:179:7
  44: core::ops::function::FnOnce::call_once
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:227:5
  45: core::ops::function::FnOnce::call_once
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'consensus_client::consensus_tests::sync_with_consensus' panicked at 'assertion failed: `(left == right)`
  left: `SequenceNumber(0)`,
 right: `SequenceNumber(2)`', sui_core/src/unit_tests/consensus_tests.rs:236:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:154:5
   4: sui_core::consensus_client::consensus_tests::sync_with_consensus::{{closure}}
             at ./src/unit_tests/consensus_tests.rs:236:5
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/future/mod.rs:84:19
   6: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/future/future.rs:123:9
   7: tokio::runtime::basic_scheduler::CoreGuard::block_on::{{closure}}::{{closure}}::{{closure}}
             at /Users/xun/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:498:48
   8: tokio::coop::with_budget::{{closure}}
             at /Users/xun/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:102:9
   9: std::thread::local::LocalKey<T>::try_with
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/thread/local.rs:412:16
  10: std::thread::local::LocalKey<T>::with
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/thread/local.rs:388:9
  11: tokio::coop::with_budget
             at /Users/xun/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:95:5
  12: tokio::coop::budget
             at /Users/xun/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:72:5
  13: tokio::runtime::basic_scheduler::CoreGuard::block_on::{{closure}}::{{closure}}
             at /Users/xun/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:498:25
  14: tokio::runtime::basic_scheduler::Context::enter
             at /Users/xun/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:356:19
  15: tokio::runtime::basic_scheduler::CoreGuard::block_on::{{closure}}
             at /Users/xun/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:497:36
  16: tokio::runtime::basic_scheduler::CoreGuard::enter::{{closure}}
             at /Users/xun/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:555:57
  17: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /Users/xun/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/macros/scoped_tls.rs:61:9
  18: tokio::runtime::basic_scheduler::CoreGuard::enter
             at /Users/xun/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:555:27
  19: tokio::runtime::basic_scheduler::CoreGuard::block_on
             at /Users/xun/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:488:9
  20: tokio::runtime::basic_scheduler::BasicScheduler::block_on
             at /Users/xun/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:168:24
  21: tokio::runtime::Runtime::block_on
             at /Users/xun/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/mod.rs:475:46
  22: sui_core::consensus_client::consensus_tests::sync_with_consensus
             at ./src/unit_tests/consensus_tests.rs:266:5
  23: sui_core::consensus_client::consensus_tests::sync_with_consensus::{{closure}}
             at ./src/unit_tests/consensus_tests.rs:179:7
  24: core::ops::function::FnOnce::call_once
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:227:5
  25: core::ops::function::FnOnce::call_once
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by patrickkuo** [comment]
Saw this failure today on master 44b5702712c15df365989a3b3f80038b7bf6c2ef


stack trace:



```
Left:  SequenceNumber(0)
Right: SequenceNumber(2)
<Click to see difference>

thread 'consensus_client::consensus_tests::sync_with_consensus' panicked at 'called `Option::unwrap()` on a `None` value', /Users/patrick/IdeaProjects/fastnft/test_utils/src/sequencer.rs:288:62
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   2: core::panicking::panic
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:48:5
   3: core::option::Option<T>::unwrap
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/option.rs:729:21
   4: test_utils::sequencer::SubscriberServer::synchronize::{{closure}}
             at /Users/patrick/IdeaProjects/fastnft/test_utils/src/sequencer.rs:288:31
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/future/mod.rs:84:19
   6: <test_utils::sequencer::SubscriberServer as sui_network::transport::MessageHandler<Stream>>::handle_messages::{{closure}}
             at /Users/patrick/IdeaProjects/fastnft/test_utils/src/sequencer.rs:331:96
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/future/mod.rs:84:19
   8: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/future/future.rs:123:9
   9: sui_network::transport::run_tcp_server::{{closure}}::{{closure}}
             at /Users/patrick/IdeaProjects/fastnft/network_utils/src/transport.rs:212:50
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/future/mod.rs:84:19
  11: tokio::runtime::task::core::CoreStage<T>::poll::{{closure}}
             at /Users/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/core.rs:161:17
  12: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /Users/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/loom/std/unsafe_cell.rs:14:9
  13: tokio::runtime::task::core::CoreStage<T>::poll
             at /Users/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/core.rs:151:13
  14: tokio::runtime::task::harness::poll_future::{{closure}}
             at /Users/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:467:19
  15: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panic/unwind_safe.rs:271:9
  16: std::panicking::try::do_call
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:406:40
  17: <unknown>
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/slice/iter/macros.rs:341:14
  18: std::panicking::try
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:370:19
  19: std::panic::catch_unwind
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panic.rs:133:14
  20: tokio::runtime::task::harness::poll_future
             at /Users/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:455:18
  21: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /Users/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:103:27
  22: tokio::runtime::task::harness::Harness<T,S>::poll
             at /Users/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/harness.rs:57:15
  23: tokio::runtime::task::raw::poll
             at /Users/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/raw.rs:128:5
  24: tokio::runtime::task::raw::RawTask::poll
             at /Users/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/raw.rs:80:18
  25: tokio::runtime::task::LocalNotified<S>::run
             at /Users/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/task/mod.rs:347:9
  26: tokio::runtime::basic_scheduler::CoreGuard::block_on::{{closure}}::{{closure}}
             at /Users/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:532:25
  27: tokio::coop::with_budget::{{closure}}
             at /Users/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:102:9
  28: std::thread::local::LocalKey<T>::try_with
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/thread/local.rs:412:16
  29: std::thread::local::LocalKey<T>::with
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/thread/local.rs:388:9
  30: tokio::coop::with_budget
             at /Users/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:95:5
  31: tokio::coop::budget
             at /Users/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:72:5
  32: tokio::runtime::basic_scheduler::Context::run_task::{{closure}}
             at /Users/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:291:29
  33: tokio::runtime::basic_scheduler::Context::enter
             at /Users/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:356:19
  34: tokio::runtime::basic_scheduler::Context::run_task
             at /Users/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:291:9
  35: tokio::runtime::basic_scheduler::CoreGuard::block_on::{{closure}}
             at /Users/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:531:34
  36: tokio::runtime::basic_scheduler::CoreGuard::enter::{{closure}}
             at /Users/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:555:57
  37: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /Users/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/macros/scoped_tls.rs:61:9
  38: tokio::runtime::basic_scheduler::CoreGuard::enter
             at /Users/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:555:27
  39: tokio::runtime::basic_scheduler::CoreGuard::block_on
             at /Users/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:488:9
  40: tokio::runtime::basic_scheduler::BasicScheduler::block_on
             at /Users/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:168:24
  41: tokio::runtime::Runtime::block_on
             at /Users/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/mod.rs:475:46
  42: sui_core::consensus_client::consensus_tests::sync_with_consensus
             at ./src/unit_tests/consensus_tests.rs:266:5
  43: sui_core::consensus_client::consensus_tests::sync_with_consensus::{{closure}}
             at ./src/unit_tests/consensus_tests.rs:179:7
  44: core::ops::function::FnOnce::call_once
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:227:5
  45: core::ops::function::FnOnce::call_once
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'consensus_client::consensus_tests::sync_with_consensus' panicked at 'assertion failed: `(left == right)`
  left: `SequenceNumber(0)`,
 right: `SequenceNumber(2)`', sui_core/src/unit_tests/consensus_tests.rs:236:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:154:5
   4: sui_core::consensus_client::consensus_tests::sync_with_consensus::{{closure}}
             at ./src/unit_tests/consensus_tests.rs:236:5
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/future/mod.rs:84:19
   6: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/future/future.rs:123:9
   7: tokio::runtime::basic_scheduler::CoreGuard::block_on::{{closure}}::{{closure}}::{{closure}}
             at /Users/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:498:48
   8: tokio::coop::with_budget::{{closure}}
             at /Users/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:102:9
   9: std::thread::local::LocalKey<T>::try_with
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/thread/local.rs:412:16
  10: std::thread::local::LocalKey<T>::with
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/thread/local.rs:388:9
  11: tokio::coop::with_budget
             at /Users/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:95:5
  12: tokio::coop::budget
             at /Users/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/coop.rs:72:5
  13: tokio::runtime::basic_scheduler::CoreGuard::block_on::{{closure}}::{{closure}}
             at /Users/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:498:25
  14: tokio::runtime::basic_scheduler::Context::enter
             at /Users/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:356:19
  15: tokio::runtime::basic_scheduler::CoreGuard::block_on::{{closure}}
             at /Users/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:497:36
  16: tokio::runtime::basic_scheduler::CoreGuard::enter::{{closure}}
             at /Users/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:555:57
  17: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /Users/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/macros/scoped_tls.rs:61:9
  18: tokio::runtime::basic_scheduler::CoreGuard::enter
             at /Users/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:555:27
  19: tokio::runtime::basic_scheduler::CoreGuard::block_on
             at /Users/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:488:9
  20: tokio::runtime::basic_scheduler::BasicScheduler::block_on
             at /Users/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/basic_scheduler.rs:168:24
  21: tokio::runtime::Runtime::block_on
             at /Users/patrick/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.17.0/src/runtime/mod.rs:475:46
  22: sui_core::consensus_client::consensus_tests::sync_with_consensus
             at ./src/unit_tests/consensus_tests.rs:266:5
  23: sui_core::consensus_client::consensus_tests::sync_with_consensus::{{closure}}
             at ./src/unit_tests/consensus_tests.rs:179:7
  24: core::ops::function::FnOnce::call_once
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:227:5
  25: core::ops::function::FnOnce::call_once
             at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

**Comment by patrickkuo** [comment]
@asonnino

**Comment by asonnino** [comment]
mmh that's strange, I will have a look and fix it
