### ISSUE TITLE
Sui fullnode container always restart

### ISSUE THREAD

**Issue by tangby** [MystenLabs/sui#11788]
## Steps to Reproduce Issue

docker-compose.yaml

---
version: "3.9"
services:
  fullnode:
    image: mysten/sui-node:stable
    ports:
    - "8084:8084/udp"
    - "9000:9000"
    - "9184:9184"
    volumes:
    - ./fullnode-template.yaml:/sui/fullnode.yaml:ro
    - ./genesis.blob:/sui/genesis.blob:ro
    - /sui/suidb:/sui/suidb:rw
    command: ["/usr/local/bin/sui-node", "--config-path", "fullnode.yaml"]
    restart: always

CONTAINER ID   IMAGE                    COMMAND                  CREATED       STATUS                            PORTS     NAMES
a1f449e29a68   mysten/sui-node:stable   "/usr/local/bin/sui-…"   9 hours ago   Restarting (139) 32 seconds ago             sui-fullnode-1

## Actual Result

2023-05-07T00:08:12.918739Z ERROR execution_driver{tx_digest=TransactionDigest(GGeSL8C9AurSPb3admcs7gqM1TRvUyTG2ZgxYqfsJdZe)}: sui_core::authority: fork detected! tx_digest=TransactionDigest(GGeSL8C9AurSPb3admcs7gqM1TRvUyTG2ZgxYqfsJdZe) expected_effects_digest=TransactionEffectsDigest(DThrHBJBRD11LDrVfo2iMVJFv4om4eDMTZWKTakvkumb) actual_effects=V1(TransactionEffectsV1 { status: Failure { error: PackageUpgradeError { upgrade_error: DigestDoesNotMatch { digest: [71, 247, 81, 172, 74, 159, 106, 168, 57, 86, 150, 216, 179, 3, 189, 172, 195, 50, 126, 152, 89, 47, 187, 130, 67, 230, 50, 113, 198, 204, 158, 24] } }, command: Some(1) }, executed_epoch: 12, gas_used: GasCostSummary { computation_cost: 5000000, storage_cost: 2622000, storage_rebate: 2595780, non_refundable_storage_fee: 26220 }, modified_at_versions: [(0x32620d6ebe191a8735d2896ce27af31e2abab613d6c56f0246cccaafa2ced7bc, SequenceNumber(22047)), (0xaa71c86834cd5cf8c8e57e3d8dafcc50f37973b4e3f13dc5f4c4c5b808b211fe, SequenceNumber(22047))], shared_objects: [], transaction_digest: TransactionDigest(GGeSL8C9AurSPb3admcs7gqM1TRvUyTG2ZgxYqfsJdZe), created: [], mutated: [((0x32620d6ebe191a8735d2896ce27af31e2abab613d6c56f0246cccaafa2ced7bc, SequenceNumber(22048), o#E9CnyKA9p6FW4vQ8FLsDk2VWMGw8g3HAe6qD7LSTtncM), AddressOwner(0xc0f7670e336119c86f4ddf0efc4b964bedaba9baca170593664e9eee31886389)), ((0xaa71c86834cd5cf8c8e57e3d8dafcc50f37973b4e3f13dc5f4c4c5b808b211fe, SequenceNumber(22048), o#EKfG97bg2K8ympWaR5Wisa2Gkg4yhJ6iG3p9fCk7QB3M), AddressOwner(0xc0f7670e336119c86f4ddf0efc4b964bedaba9baca170593664e9eee31886389))], unwrapped: [], deleted: [], unwrapped_then_deleted: [], wrapped: [], gas_object: ((0x32620d6ebe191a8735d2896ce27af31e2abab613d6c56f0246cccaafa2ced7bc, SequenceNumber(22048), o#E9CnyKA9p6FW4vQ8FLsDk2VWMGw8g3HAe6qD7LSTtncM), AddressOwner(0xc0f7670e336119c86f4ddf0efc4b964bedaba9baca170593664e9eee31886389)), events_digest: None, dependencies: [TransactionDigest(3wz9rYNpCp8dsy3E1iLe4L5v8qxMcJPB7sAato6835nE), TransactionDigest(5xhjyjuhuPFVFLcVWNJDh9qz2QaCDBPd1bnSs43dG3H2), TransactionDigest(8Vrbq9Q9sm1daDqhAaV3vhckB189yjuyrVeHPHxg29xp), TransactionDigest(B9u8qs66Q5pCDa8viSnc7nxn5oJYpqUphx74LiFUMHZK), TransactionDigest(CYyn7sm7RVw5LVfDVsp2J4RmcUxfBSXBCReFPtn9KCst), TransactionDigest(Hg9UfnkvvFpBqgW3w2CKR3DJ1m5Ue81Evt1FXa9pQKus), TransactionDigest(J8wXT4xGrFiZ8QCL9Sds1AbEfGR37rHugG6oayTEv7oG)] })
2023-05-07T00:08:12.920268Z ERROR execution_driver{tx_digest=TransactionDigest(GGeSL8C9AurSPb3admcs7gqM1TRvUyTG2ZgxYqfsJdZe)}: telemetry_subscribers: panicked at 'Transaction GGeSL8C9AurSPb3admcs7gqM1TRvUyTG2ZgxYqfsJdZe is expected to have effects digest DThrHBJBRD11LDrVfo2iMVJFv4om4eDMTZWKTakvkumb, but got 2QULCKZaCF1NQ9aZXiWhUEfVP4gG7HDCYACZyD4wy4mD!', /sui/crates/sui-core/src/authority.rs:892:17 panic.file="/sui/crates/sui-core/src/authority.rs" panic.line=892 panic.column=17
thread 'sui-node-runtime' panicked at 'Transaction GGeSL8C9AurSPb3admcs7gqM1TRvUyTG2ZgxYqfsJdZe is expected to have effects digest DThrHBJBRD11LDrVfo2iMVJFv4om4eDMTZWKTakvkumb, but got 2QULCKZaCF1NQ9aZXiWhUEfVP4gG7HDCYACZyD4wy4mD!', /sui/crates/sui-core/src/authority.rs:892:17

## System Information

* OS: Ubuntu 22.04 LTS
* Compiler: docker v23.0.5

**Comment by tangby** [comment]
stack backtrace:
   0:     0x559cbd1ec64a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he1c117e52d53614f
   1:     0x559cbd216f2e - core::fmt::write::h25eb51b9526b8e0c
   2:     0x559cbd1e5985 - std::io::Write::write_fmt::ha9edec5fb1621933
   3:     0x559cbd1ec415 - std::sys_common::backtrace::print::h41b9b18ed86f86bd
   4:     0x559cbd1edeaf - std::panicking::default_hook::{{closure}}::h22a91871f4454152
   5:     0x559cbd1edbeb - std::panicking::default_hook::h21ddc36de0cd4ae7
   6:     0x559cbba613ac - telemetry_subscribers::set_panic_hook::{{closure}}::h326c49534bd7db5a
   7:     0x559cbd1ee5da - std::panicking::rust_panic_with_hook::h5059419d6d59b3d0
   8:     0x559cbd1ee359 - std::panicking::begin_panic_handler::{{closure}}::h0f383c291cd78343
   9:     0x559cbd1ecafc - std::sys_common::backtrace::__rust_end_short_backtrace::h70ab22f2ad318cdd
  10:     0x559cbd1ee062 - rust_begin_unwind
  11:     0x559cbac323a3 - core::panicking::panic_fmt::hd1d46bcde3c61d72
  12:     0x559cbaf18a15 - sui_core::authority::AuthorityState::process_certificate::{{closure}}::{{closure}}::h98cba4d7ea81d301
  13:     0x559cbaf19f91 - sui_core::authority::AuthorityState::try_execute_immediately::{{closure}}::{{closure}}::h6c88236154936b2e
  14:     0x559cbaf18fbf - sui_core::authority::AuthorityState::try_execute_immediately::{{closure}}::hac48798bef250c49
  15:     0x559cbaf33584 - <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll::h60db79ef59fc28b5
  16:     0x559cbb1d16a1 - sui_core::execution_driver::execution_process::{{closure}}::{{closure}}::he43e63f3c44abdf2
  17:     0x559cbadb6ac5 - tokio::runtime::task::core::Core<T,S>::poll::h1509adfa44727d51
  18:     0x559cbb062b87 - tokio::runtime::task::harness::Harness<T,S>::poll::hbcbe1f6115a3a8fe
  19:     0x559cbd15803b - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::he092663116ea62bd
  20:     0x559cbd15764e - tokio::runtime::scheduler::multi_thread::worker::Context::run::h84d1e1b3c3595bc2
  21:     0x559cbd157128 - tokio::runtime::scheduler::multi_thread::worker::run::h159019b3880d61c7
  22:     0x559cbd1716c2 - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::hde15e8b2683a3835
  23:     0x559cbd16369a - tokio::runtime::task::core::Core<T,S>::poll::hac9760022355fdc2
  24:     0x559cbd1531ca - tokio::runtime::task::harness::Harness<T,S>::poll::h24c74eaee0e08b41
  25:     0x559cbd15ebb5 - tokio::runtime::blocking::pool::Inner::run::h34b67848907caaab
  26:     0x559cbd164af4 - std::sys_common::backtrace::__rust_begin_short_backtrace::h804ae8ed368c4c7a
  27:     0x559cbd155d0f - core::ops::function::FnOnce::call_once{{vtable.shim}}::h02932da077948ca7
  28:     0x559cbd1f4753 - std::sys::unix::thread::Thread::new::thread_start::had7b8061e306bb5c
  29:     0x7f5a8f6f5ea7 - start_thread
  30:     0x7f5a8f4c9a2f - clone
  31:                0x0 - <unknown>
