### ISSUE TITLE
getBalance results to RPCValidationError

### ISSUE THREAD

**Issue by asir6** [MystenLabs/sui#12353]
Was writing a simple application to get sui balance of a particular address

"@mysten/sui.js": "^0.30.0"

```
const { JsonRpcProvider } = require('@mysten/sui.js');
const provider = new JsonRpcProvider();
const coinBalance = await provider.getBalance({
    owner: 'address'
});
```

But get following error 
```
RPCValidationError: RPC Validation Error: The response returned from RPC server does not match the TypeScript definition. This is likely because the SDK version is not compatible with the RPC server.
    at JsonRpcClient.requestWithType (.\node_modules\@mysten\sui.js\dist\index.js:2295:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    ... 2 lines matching cause stack trace ...
    at async main (.\playground.js:411:9) {
  req: {
    method: 'suix_getBalance',
    args: [
      'address',
      undefined
    ]
  },
  result: {
    coinType: '0x2::sui::SUI',
    coinObjectCount: 0,
    totalBalance: '0',
    lockedBalance: {}
  },
  [cause]: StructError: At path: totalBalance -- Expected a number, but received: "0"
      at validate (.\node_modules\superstruct\dist\index.cjs:301:27)
      at JsonRpcClient.requestWithType (.\node_modules\@mysten\sui.js\dist\index.js:2292:55)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async JsonRpcProvider.getBalance (.\node_modules\@mysten\sui.js\dist\index.js:3890:12)```

**Comment by Jordan-Mysten** [comment]
You'll likely need to update your `@mysten/sui.js` version, as the format of this data has changed
