### ISSUE TITLE
[move][dependency graph] dependency graph panics on a package with a top-level override of a nested dependency

### ISSUE THREAD

**Issue by kklas** [MystenLabs/sui#13940]
## Steps to Reproduce Issue

Check out https://github.com/MystenLabs/sui/compare/main...kklas:sui:dep-graph-panic and run `sui move build` within the `nested_deps_top_level_override` directory. It will panic.

## Expected Result

To build the package.

This is a dependency graph that is very common -- e.g., you can think of "C" as `Sui`  and "D" as `MoveStdlib` (see attachment below).

## Actual Result

Panics:

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', external-crates/move/tools/move-package/src/resolution/dependency_graph.rs:1507:72
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2023-09-24T22:01:29.076530Z ERROR telemetry_subscribers: panicked at 'called `Option::unwrap()` on a `None` value', external-crates/move/tools/move-package/src/resolution/dependency_graph.rs:1507:72 panic.file="external-crates/move/tools/move-package/src/resolution/dependency_graph.rs" panic.line=1507 panic.column=72
Aborted (core dumped)
```

## System Information

* OS: linux
* Compiler: `sui 1.10.1-a0e136a`

## Attachment
This is the dependency graph in question:

```
# ┌─────────┐           ┌─────────┐     ┌────────┐      ┌────────┐
# │         │           │         │     │        │      │        │
# │  ROOT   ├────┬─────►│   A     ├────►│   C    ├─────►│   D    │
# │         │    │      │         │     │        │      │        │
# └─────────┘    │      └─────────┘     └───▲────┘      └───▲────┘
#                │                          │               │
#                │      ┌─────────┐         │               │
#                │      │         │         │               │
#                ├─────►│   B     ├─────────┘               │
#                │      │         │                         │
#                │      └─────────┘                         │
#                │                                          │
#                │      ┌─────────┐                         │
#                │      │         │       override          │
#                └─────►│   D2    ├─────────────────────────┘
#                       │         │
#                       └─────────┘
```

**Comment by kklas** [comment]
Solved by #13921
