### ISSUE TITLE
recent image after c34474de26c613d0e36741c66bc65c1f854fb847 breaking on "telemetry_subscribers: panicked / no CA certificates found" 

### ISSUE THREAD

**Issue by jun0tpyrc** [MystenLabs/sui#16586]
this tag is good
docker pull mysten/sui-node:c34474de26c613d0e36741c66bc65c1f854fb847

soon after some commit post that tag , need some working_dir alignment to make things work , but would still hit

```
2024-03-11T05:04:11.068631Z  INFO sui_storage::http_key_value_store: creating HttpKVStore with base_url: https://transactions.sui.io/mainnet
thread 'sui-node-runtime' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-rustls-0.24.0/src/config.rs:48:9:
no CA certificates found
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2024-03-11T05:04:11.070212Z ERROR telemetry_subscribers: panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-rustls-0.24.0/src/config.rs:48:9:
no CA certificates found panic.file="/root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hyper-rustls-0.24.0/src/config.rs" panic.line=48 panic.column=9
```

**Comment by jun0tpyrc** [comment]
it's solved with latest mysten/sui-node:ci
