### ISSUE TITLE
Can't get gas profile from testnet

### ISSUE THREAD

**Issue by EasonC13** [MystenLabs/sui#17314]
I tried to get transaction profile on testnet and devnet with the following cli command, but it is not working:

```
> sui --version
sui 1.22.0-2d07a1fd9f
```

```
sui client switch --env testnet && sui client profile-transaction --tx-digest DdjRK3L7RkzwV5N2PPJUCy5UVvbwK9zcqSm65ge4Bvzr
```

```
2024-04-24T11:52:46.937132Z  INFO sui_replay::replay: Using RPC URL: https://fullnode.testnet.sui.io:443
2024-04-24T11:53:03.669518Z  WARN sui_replay::replay: Object 0x0000000000000000000000000000000000000000000000000000000000000003 at version 0x4 does not exist on RPC server. This might be due to pruning. Historical replays might not work
thread '2024-04-24T11:53:04.878847Z ERROR telemetry_subscribers: panicked at crates/sui-protocol-config/src/lib.rs:1211:9:
Network protocol version is ProtocolVersion(43), but the maximum supported version by the binary is 42. Please upgrade the binary. panic.file="crates/sui-protocol-config/src/lib.rs" panic.line=1211 panic.column=9
main' panicked at crates/sui-protocol-config/src/lib.rs:1211:9:
Network protocol version is ProtocolVersion(43), but the maximum supported version by the binary is 42. Please upgrade the binary.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[1]    65174 abort      /Users/user/.cargo/bin/sui client profile-transaction --tx-digest
```

**Comment by EasonC13** [comment]
I tried to upgrade cli to 1.23.1. Now I got the following error:

```
2024-04-24T12:29:35.714738Z  INFO sui_replay: Executing tx: DdjRK3L7RkzwV5N2PPJUCy5UVvbwK9zcqSm65ge4Bvzr
2024-04-24T12:29:35.714959Z  INFO sui_replay::replay: Using RPC URL: https://fullnode.testnet.sui.io:443
2024-04-24T12:30:03.086177Z  WARN sui_replay::replay: Object 0x0000000000000000000000000000000000000000000000000000000000000003 at version 0x4 does not exist on RPC server. This might be due to pruning. Historical replays might not work
cli2024-04-24T12:30:06.221443Z  INFO move_vm_profiler: No meaningful gas usage for this transaction, it may be a system transaction
Execution finished successfully.
```

Yet I use another transaction and success.

```
sui client profile-transaction --tx-digest 4Qff4WTGnKwwsztY2Mk8EosjJYxD2QBsbKmCdu7bpZqu
```

Simply put, Sui Cli requires a protocol version that is greater than or equal to the one specified in order to be used.

I tried upgrading to the testnet version, and it worked on both the testnet and mainnet. However, if I use only the mainnet version, it will only work on the mainnet and not on the testnet.

Correct me if I'm wrong.
