### ISSUE TITLE
The CoinWithBalance intent - TypeError: Expected object with one key, but found 0 for type Command}

### ISSUE THREAD

**Issue by igdeman** [MystenLabs/sui#18247]
I have tried to use "coinWithBalance" function like described in the documentation. Unfortunately i'm getting error. Below is the minimal example to reproduce error:

```
import { Transaction, coinWithBalance } from "@mysten/sui/transactions";
import { SuiClient, getFullnodeUrl } from "@mysten/sui/client";

const sender = Ed25519Keypair.deriveKeypair("<mnemonic>")
const client = new SuiClient({ url: getFullnodeUrl("mainnet") })
const tx = new Transaction();
tx.transferObjects([coinWithBalance({ balance: 100n })], "<recepient>");
tx.setSender(sender.getPublicKey().toSuiAddress());
tx.sign({ signer: sender, client })
const txBytes = await tx.build({ client });
```

Instead of transaction bytes i'm getting following error:
```
TypeError: Expected object with one key, but found 0 for type Command}

      at _BcsType.validate (node_modules/@mysten/sui/node_modules/@mysten/bcs/src/bcs.ts:516:12)
      at _BcsType.write (node_modules/@mysten/sui/node_modules/@mysten/bcs/src/bcs-type.ts:56:8)
      at _BcsType.write (node_modules/@mysten/sui/node_modules/@mysten/bcs/src/bcs.ts:288:11)
      at _BcsType.write (node_modules/@mysten/sui/node_modules/@mysten/bcs/src/bcs-type.ts:57:3)
      at _BcsType.write (node_modules/@mysten/sui/node_modules/@mysten/bcs/src/bcs.ts:428:11)
      at _BcsType.write (node_modules/@mysten/sui/node_modules/@mysten/bcs/src/bcs-type.ts:57:3)
      at _BcsType.write (node_modules/@mysten/sui/node_modules/@mysten/bcs/src/bcs.ts:499:19)
      at _BcsType.write (node_modules/@mysten/sui/node_modules/@mysten/bcs/src/bcs-type.ts:57:3)
      at _BcsType.write (node_modules/@mysten/sui/node_modules/@mysten/bcs/src/bcs.ts:428:11)
      at _BcsType.write (node_modules/@mysten/sui/node_modules/@mysten/bcs/src/bcs-type.ts:57:3)
      at _BcsType.write (node_modules/@mysten/sui/node_modules/@mysten/bcs/src/bcs.ts:499:19)
      at _BcsType.<anonymous> (node_modules/@mysten/sui/node_modules/@mysten/bcs/src/bcs-type.ts:48:5)
      at _BcsType.serialize (node_modules/@mysten/sui/node_modules/@mysten/bcs/src/bcs-type.ts:62:34)
      at TransactionDataBuilder.build (node_modules/@mysten/sui/src/transactions/TransactionData.ts:190:30)
      at setGasBudget (node_modules/@mysten/sui/src/transactions/json-rpc-resolver.ts:73:37)
      at resolveTransactionData (node_modules/@mysten/sui/src/transactions/json-rpc-resolver.ts:48:9)
      at async /Users/igdeman/Work/DigitalMind/telegram/sui-telegram-wallet/node_modules/@mysten/sui/src/transactions/Transaction.ts:504:5
      at async _Transaction.runPlugins_fn (node_modules/@mysten/sui/src/transactions/Transaction.ts:526:3)
      at async _Transaction.prepareBuild_fn (node_modules/@mysten/sui/src/transactions/Transaction.ts:489:3)
      at async _Transaction.build (node_modules/@mysten/sui/src/transactions/Transaction.ts:464:3)
      at async _Transaction.sign (node_modules/@mysten/sui/src/transactions/Transaction.ts:457:17)
```

## System Information
* OS: MacOS
* Package: @mysten/sui v1.1.1

**Comment by hayes-mysten** [comment]
thanks for reporting this, fix should be out soon

**Comment by hayes-mysten** [comment]
fix is published on npm
