### ISSUE TITLE
Type Layout resolver issue

### ISSUE THREAD

**Issue by alexanderludwig** [MystenLabs/sui#19381]
## Steps to Reproduce Issue

```
let init_tag = StructTag {
                address: AccountAddress::from_hex_literal(&config.sui_deployed_state_proof_package)
                    .unwrap(),
                module: Identifier::new("dwallet_cap").expect("can't create identifier"),
                name: Identifier::new("DWalletNetworkInitCapRequest")
                    .expect("can't create identifier"),
                type_params: vec![],
            };
  println!("Init Tag: {}", init_tag);

  let init_type_layout = resolver
              .type_layout(TypeTag::Struct(Box::new(init_tag)))
              .await
              .unwrap();

```

- For this package id the resolving works: 0xda072e51bf74040f2f99909595ef1db40fdc75071b92438bb9864f6c744c6736 (deployed a few months ago)
- However for this package id it fails: 0x0bde775d63aa25d1fb0df56b71acc516d746ea8d79a89a6dc7c9039e0bd41db6 (deployed yesterday)

Could be related to the bytecode changes. 

## Expected Result

Resolving both package ids should work.

## Actual Result

Init Tag: 0xbde775d63aa25d1fb0df56b71acc516d746ea8d79a89a6dc7c9039e0bd41db6::dwallet_cap::DWalletNetworkInitCapRequest
```
thread 'main' panicked at src/light-client/light-client.rs:128:73:
called `Result::unwrap()` on an `Err` value: Checkpoint sequence number does not match. Need to Sync.

Stack backtrace:
   0: std::backtrace_rs::backtrace::libunwind::trace
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/../../backtrace/src/backtrace/libunwind.rs:105:5
   1: std::backtrace_rs::backtrace::trace_unsynchronized
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2: std::backtrace::Backtrace::create
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/backtrace.rs:331:13
   3: anyhow::error::<impl anyhow::Error>::msg
             at /Users/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/anyhow-1.0.86/src/error.rs:83:36
   4: anyhow::__private::format_err
             at /Users/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/anyhow-1.0.86/src/lib.rs:689:13
   5: light_client::get_verified_effects_and_events::{{closure}}
             at ./src/light-client/light-client.rs:715:9
   6: light_client::get_verified_object::{{closure}}
             at ./src/light-client/light-client.rs:764:93
   7: <light_client::RemotePackageStore as sui_package_resolver::PackageStore>::fetch::{{closure}}
             at ./src/light-client/light-client.rs:128:67
   8: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/future/future.rs:123:9
   9: sui_package_resolver::ResolutionContext::add_type_tag::{{closure}}
             at /Users/alex/.cargo/git/checkouts/sui-6ac459c53b1b685a/c79f53f/crates/sui-package-resolver/src/lib.rs:1195:58
  10: sui_package_resolver::Resolver:type_layout:{{closure}}
             at /Users/alex/.cargo/git/checkouts/sui-6ac459c53b1b685a/c79f53f/crates/sui-package-resolver/src/lib.rs:364:14
  11: light_client::main::{{closure}}
             at ./src/light-client/light-client.rs:1221:18
  12: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/future/future.rs:123:9
  13: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /Users/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/park.rs:281:63
  14: tokio::runtime::coop::with_budget
             at /Users/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/coop.rs:107:5
  15: tokio::runtime::coop::budget
             at /Users/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/coop.rs:73:5
  16: tokio::runtime::park::CachedParkThread::block_on
             at /Users/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/park.rs:281:31
  17: tokio::runtime::context::blocking::BlockingRegionGuard::block_on
             at /Users/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/context/blocking.rs:66:9
  18: tokio::runtime::scheduler::multi_thread::MultiThread::block_on::{{closure}}
             at /Users/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/scheduler/multi_thread/mod.rs:87:13
  19: tokio::runtime::context::runtime::enter_runtime
             at /Users/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/context/runtime.rs:65:16
  20: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at /Users/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/scheduler/multi_thread/mod.rs:86:9
  21: tokio::runtime::runtime::Runtime::block_on_inner
             at /Users/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/runtime.rs:363:45
  22: tokio::runtime::runtime::Runtime::block_on
             at /Users/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/runtime.rs:333:13
  23: light_client::main
             at ./src/light-client/light-client.rs:1578:5
  24: core::ops::function::FnOnce::call_once
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/ops/function.rs:250:5
  25: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/sys_common/backtrace.rs:155:18
  26: std::rt::lang_start::{{closure}}
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/rt.rs:166:18
  27: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/ops/function.rs:284:13
  28: std::panicking::try::do_call
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:552:40
  29: std::panicking::try
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:516:19
  30: std::panic::catch_unwind
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panic.rs:146:14
  31: std::rt::lang_start_internal::{{closure}}
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/rt.rs:148:48
  32: std::panicking::try::do_call
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:552:40
  33: std::panicking::try
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:516:19
  34: std::panic::catch_unwind
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panic.rs:146:14
  35: std::rt::lang_start_internal
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/rt.rs:148:20
  36: std::rt::lang_start
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/rt.rs:165:17
  37: _main
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/result.rs:1654:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/result.rs:1077:23
   4: <light_client::RemotePackageStore as sui_package_resolver::PackageStore>::fetch::{{closure}}
             at ./src/light-client/light-client.rs:128:22
   5: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/future/future.rs:123:9
   6: sui_package_resolver::ResolutionContext::add_type_tag::{{closure}}
             at /Users/alex/.cargo/git/checkouts/sui-6ac459c53b1b685a/c79f53f/crates/sui-package-resolver/src/lib.rs:1195:58
   7: sui_package_resolver::Resolver
             at /Users/alex/.cargo/git/checkouts/sui-6ac459c53b1b685a/c79f53f/crates/sui-package-resolver/src/lib.rs:364:14
   8: light_client::main::{{closure}}
             at ./src/light-client/light-client.rs:1221:18
   9: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/future/future.rs:123:9
  10: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /Users/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/park.rs:281:63
  11: tokio::runtime::coop::with_budget
             at /Users/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/coop.rs:107:5
  12: tokio::runtime::coop::budget
             at /Users/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/coop.rs:73:5
  13: tokio::runtime::park::CachedParkThread::block_on
             at /Users/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/park.rs:281:31
  14: tokio::runtime::context::blocking::BlockingRegionGuard::block_on
             at /Users/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/context/blocking.rs:66:9
  15: tokio::runtime::scheduler::multi_thread::MultiThread::block_on::{{closure}}
             at /Users/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/scheduler/multi_thread/mod.rs:87:13
  16: tokio::runtime::context::runtime::enter_runtime
             at /Users/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/context/runtime.rs:65:16
  17: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at /Users/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/scheduler/multi_thread/mod.rs:86:9
  18: tokio::runtime::runtime::Runtime::block_on_inner
             at /Users/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/runtime.rs:363:45
  19: tokio::runtime::runtime::Runtime::block_on
             at /Users/alex/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.39.2/src/runtime/runtime.rs:333:13
  20: light_client::main
             at ./src/light-client/light-client.rs:1578:5
  21: core::ops::function::FnOnce::call_once
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
## System Information

* OS: newest mac
* importing packages from this rev: e.g.  move-core-types = { git = "https://github.com/MystenLabs/sui", package = "move-core-types", rev="c79f53f" }

**Comment by gdanezis** [comment]
> Checkpoint sequence number does not match. Need to Sync.

This part of the error seems to indicate that the light client does not have the latest epoch committee maybe? Did you try to run the 'sync' command? 

What exact command line did you use that led to this error?

**Comment by alexanderludwig** [comment]
Hi George, thanks for looking into this. 

The error message is misleading, the error occurs when resolving the type layout (but only for the package id of the recently deployed package)
Modified your version of the light client to work with dWallet. This is our repo and the line where the error itself occurs: https://github.com/aeon-protocol/sui-light-client/blob/main/src/light-client/light-client.rs#L1218

**Comment by gdanezis** [comment]
Ok got it, so the latest update of the light client on the main Sui repo is unlikely to be the cause of this issue if you have your own fork.

**Comment by amnn** [comment]
I don't think this is really related to type layout resolution. It just so happens that the package resolver is the one that is trying to fetch an object (the package containing the type), but the underlying issue is related to how a light client reads objects (going back to @gdanezis' original comment).

**Comment by alexanderludwig** [comment]
Ok let me confirm that this is not an issue introduced on our end.

**Comment by alexanderludwig** [comment]
Ok the issue was on our end, thanks for looking into this though!

**Comment by gdanezis** [comment]
Most welcome!
