### ISSUE TITLE
'authority_server::server_tests::test_subscription' flacky

### ISSUE THREAD

**Issue by lxfind** [MystenLabs/sui#1957]
I sometimes see this test failure:
```
thread 'authority_server::server_tests::test_subscription' panicked at 'assertion failed: `(left == right)`
  left: `2`,
 right: `3`', sui_core/src/unit_tests/server_tests.rs:256:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:182:5
   4: sui_core::authority_server::server_tests::test_subscription::{{closure}}
             at ./src/unit_tests/server_tests.rs:256:5
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
   6: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/future.rs:123:9
   7: tokio::runtime::basic_scheduler::CoreGuard::block_on::{{closure}}::{{closure}}::{{closure}}
             at /Users/xun/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/basic_scheduler.rs:507:48
   8: tokio::coop::with_budget::{{closure}}
             at /Users/xun/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/coop.rs:102:9
   9: std::thread::local::LocalKey<T>::try_with
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/thread/local.rs:413:16
  10: std::thread::local::LocalKey<T>::with
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/thread/local.rs:389:9
  11: tokio::coop::with_budget
             at /Users/xun/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/coop.rs:95:5
  12: tokio::coop::budget
             at /Users/xun/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/coop.rs:72:5
  13: tokio::runtime::basic_scheduler::CoreGuard::block_on::{{closure}}::{{closure}}
             at /Users/xun/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/basic_scheduler.rs:507:25
  14: tokio::runtime::basic_scheduler::Context::enter
             at /Users/xun/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/basic_scheduler.rs:361:19
  15: tokio::runtime::basic_scheduler::CoreGuard::block_on::{{closure}}
             at /Users/xun/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/basic_scheduler.rs:506:36
  16: tokio::runtime::basic_scheduler::CoreGuard::enter::{{closure}}
             at /Users/xun/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/basic_scheduler.rs:564:57
  17: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /Users/xun/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/macros/scoped_tls.rs:61:9
  18: tokio::runtime::basic_scheduler::CoreGuard::enter
             at /Users/xun/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/basic_scheduler.rs:564:27
  19: tokio::runtime::basic_scheduler::CoreGuard::block_on
             at /Users/xun/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/basic_scheduler.rs:497:9
  20: tokio::runtime::basic_scheduler::BasicScheduler::block_on
             at /Users/xun/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/basic_scheduler.rs:173:24
  21: tokio::runtime::Runtime::block_on
             at /Users/xun/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.18.2/src/runtime/mod.rs:475:46
  22: sui_core::authority_server::server_tests::test_subscription
             at ./src/unit_tests/server_tests.rs:259:5
  23: sui_core::authority_server::server_tests::test_subscription::{{closure}}
             at ./src/unit_tests/server_tests.rs:89:7
  24: core::ops::function::FnOnce::call_once
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:227:5
  25: core::ops::function::FnOnce::call_once
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by huitseeker** [comment]
Yep, it occured in the completely benign CI PR:
https://github.com/MystenLabs/sui/pull/1941
see run:
https://github.com/MystenLabs/sui/runs/6426849219?check_suite_focus=true
Saved logs:
https://gist.github.com/huitseeker/df31345d92b3f19d5a747aed821c0b02
/cc @asonnino

**Comment by asonnino** [comment]
Yes it happens all the time to me as well. Copying here @huitseeker way to reproduce this kind of errors:
```bash
while true; do RUST_BACKTRACE=full cargo nextest run  -p sui_core test_subscription || break; done
```

**Comment by gdanezis** [comment]
Yes, I am on it.

**Comment by oxade** [comment]
Seeing this issue again on local
