### ISSUE TITLE
signAndExecuteTransaction Error 

### ISSUE THREAD

**Issue by wowok-ai** [MystenLabs/sui#19830]
```
const ret:any = await wallet.signAndExecuteTransaction({transaction:props.txb});
```

```
Error: Rejected from user
    at dapp-interface.js:1:60615
    at dapp-interface.js:1:16150
    at a._next (dapp-interface.js:1:15584)
    at t.next (dapp-interface.js:1:8270)
    at dapp-interface.js:1:60532
    at a._next (dapp-interface.js:1:15584)
    at t.next (dapp-interface.js:1:8270)
    at dapp-interface.js:1:16143
    at a._next (dapp-interface.js:1:15584)
    at t.next (dapp-interface.js:1:8270)
```

During the use of wallet-kit, the wallet UI will flash twice, and the signature transaction will eventually succeed, but an exception will still be thrown.

**Comment by hayes-mysten** [comment]
If you are using suit-wallet kit, the correct repo to report issues is here: https://github.com/suiet/wallet-kit

If you are using mysten/wallet-kit, this has been deprecated and replaced by [dapp-kit](https://sdk.mystenlabs.com/dapp-kit/)

There isn't enough information in this error report to tell what library you are using, or what might be going wrong
