### ISSUE TITLE
Test `shared_object_sync` fails sometimes

### ISSUE THREAD

**Issue by lxfind** [MystenLabs/sui#2530]
Seeing the following error sometimes:
```
--- STDERR:                            sui::shared_objects_tests shared_object_sync ---
thread 'shared_object_sync' panicked at 'called `Result::unwrap_err()` on an `Ok` value: TransactionEffects { status: Success { gas_cost: GasCostSummary { computation_cost: 187, storage_cost: 30, storage_rebate: 15 } }, shared_objects: [(0x9e5c12f6c097f0d564a5500dedb956c6e4f2e7fa, SequenceNumber(1), o#28e990ece0a0c3bb9164774b2f29ccaacff0b4f003e0f03b30148c61d2df4974)], transaction_digest: p3uReba8P7BKZHW6qJ1lJUMBamjO01aHChInFaIBlNo=, created: [], mutated: [((0x0000000000000000000000004444444444444446, SequenceNumber(1), o#9f68aea2f20daf794e5da37bf4c323ecfd9cd942c63b765d08564eaf98fa9237), AddressOwner(0x980e3ea6ccd6feabc74e40cb715bcaa29d4eb768)), ((0x9e5c12f6c097f0d564a5500dedb956c6e4f2e7fa, SequenceNumber(2), o#af4cd07a8985e9cce79f904d0612503f3b6854414578db74122a3bda172a8d64), Shared)], unwrapped: [], deleted: [], wrapped: [], gas_object: ((0x0000000000000000000000004444444444444446, SequenceNumber(1), o#9f68aea2f20daf794e5da37bf4c323ecfd9cd942c63b765d08564eaf98fa9237), AddressOwner(0x980e3ea6ccd6feabc74e40cb715bcaa29d4eb768)), events: [], dependencies: [U0CE95OW+wUIa0rZwoDYL9RFlyFvLlQSzie13dtfY40=, cYI7xSWAg//NFO/f1oWcbbrw8OqcIlCR/v2UpungNyg=] }', crates/sui/tests/shared_objects_tests.rs:277:6
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: core::result::unwrap_failed
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/result.rs:1749:5
   3: core::result::Result<T,E>::unwrap_err
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/result.rs:1161:22
   4: shared_objects_tests::shared_object_sync::{{closure}}
             at ./tests/shared_objects_tests.rs:272:16
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/mod.rs:84:19
   6: <core::pin::Pin<P> as core::future::future::Future>::poll
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/future/future.rs:123:9
   7: tokio::runtime::basic_scheduler::CoreGuard::block_on::{{closure}}::{{closure}}::{{closure}}
             at /Users/xun/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.1/src/runtime/basic_scheduler.rs:508:48
   8: tokio::coop::with_budget::{{closure}}
             at /Users/xun/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.1/src/coop.rs:102:9
   9: std::thread::local::LocalKey<T>::try_with
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/thread/local.rs:413:16
  10: std::thread::local::LocalKey<T>::with
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/thread/local.rs:389:9
  11: tokio::coop::with_budget
             at /Users/xun/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.1/src/coop.rs:95:5
  12: tokio::coop::budget
             at /Users/xun/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.1/src/coop.rs:72:5
  13: tokio::runtime::basic_scheduler::CoreGuard::block_on::{{closure}}::{{closure}}
             at /Users/xun/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.1/src/runtime/basic_scheduler.rs:508:25
  14: tokio::runtime::basic_scheduler::Context::enter
             at /Users/xun/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.1/src/runtime/basic_scheduler.rs:362:19
  15: tokio::runtime::basic_scheduler::CoreGuard::block_on::{{closure}}
             at /Users/xun/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.1/src/runtime/basic_scheduler.rs:507:36
  16: tokio::runtime::basic_scheduler::CoreGuard::enter::{{closure}}
             at /Users/xun/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.1/src/runtime/basic_scheduler.rs:565:57
  17: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /Users/xun/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.1/src/macros/scoped_tls.rs:61:9
  18: tokio::runtime::basic_scheduler::CoreGuard::enter
             at /Users/xun/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.1/src/runtime/basic_scheduler.rs:565:27
  19: tokio::runtime::basic_scheduler::CoreGuard::block_on
             at /Users/xun/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.1/src/runtime/basic_scheduler.rs:498:9
  20: tokio::runtime::basic_scheduler::BasicScheduler::block_on
             at /Users/xun/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.1/src/runtime/basic_scheduler.rs:174:24
  21: tokio::runtime::Runtime::block_on
             at /Users/xun/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.19.1/src/runtime/mod.rs:480:46
  22: shared_objects_tests::shared_object_sync
             at ./tests/shared_objects_tests.rs:294:5
  23: shared_objects_tests::shared_object_sync::{{closure}}
             at ./tests/shared_objects_tests.rs:220:7
  24: core::ops::function::FnOnce::call_once
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:227:5
  25: core::ops::function::FnOnce::call_once
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/ops/function.rs:227:5
```

**Comment by lxfind** [comment]
Example: https://github.com/MystenLabs/sui/runs/6883952683?check_suite_focus=true

**Comment by lxfind** [comment]
Unfortunately I still see the error sometimes
