### ISSUE TITLE
Sui Fullnode issue on startup with the last devnet development

### ISSUE THREAD

**Issue by rsilvestre** [MystenLabs/sui#3830]
## Steps to Reproduce Issue

Following the official update procedure :

```shell
$ cargo run --release --bin sui-node -- --config-path fullnode.yaml
```

```shell
Finished release [optimized] target(s) in 0.75s
Running `target/release/sui-node --config-path fullnode.yaml`
2022-08-08T08:06:13.252826Z  INFO sui_node: Default Jemalloc conf:
2022-08-08T08:06:13.253323Z  INFO sui_node::admin: starting admin server filter=info address=127.0.0.1:1337
2022-08-08T08:06:13.253387Z  INFO sui_node: Starting Prometheus HTTP endpoint at 0.0.0.0:9184
2022-08-08T08:06:13.253429Z  INFO sui_node: Initializing sui-node listening on /dns/localhost/tcp/8080/http node=k#9bd3e78fb250bdd923e0e009e14582e08e75d54c9b9e0216feaa6c51ae9c3d1a
2022-08-08T08:06:13.253976Z  INFO sui_node: Jemalloc: 6 MB allocated / 9 MB resident
2022-08-08T08:06:13.321697Z  INFO sui_storage::lock_service: LockService command processing loop started
2022-08-08T08:06:13.322533Z  INFO sui_storage::lock_service: LockService queries processing loop started
thread '2022-08-08T08:06:13.460176Z ERROR telemetry_subscribers: panicked at 'called `Option::unwrap()` on a `None` value', /home/admin/sui/crates/sui-core/src/authority/authority_store.rs:1365:14 panic.file="/home/admin/sui/crates/sui-core/src/authority/authority_store.rs" panic.line=1365 panic.column=14
main' panicked at 'called `Option::unwrap()` on a `None` value', /home/admin/sui/crates/sui-core/src/authority/authority_store.rs:1365:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
2022-08-08T08:06:13.462043Z  INFO sui_storage::lock_service: LockService command loop stopped, the sender on other end hung up/dropped
2022-08-08T08:06:13.462052Z  INFO sui_storage::lock_service: LockService queries loop stopped, the sender on other end hung up/dropped
```

## Result

Application crash

## Expected state

Application up and running

## System Information

* OS: Debian 11.4
* Compiler: rustc 1.62.1

**Comment by rsilvestre** [comment]
I just have to delete suidb
