### ISSUE TITLE
[Flaky-test] end_to_end_with_one_byzantine

### ISSUE THREAD

**Issue by velvia** [MystenLabs/sui#4437]
## Steps to Reproduce Issue

This test regularly fails

```
1.20.1/src/runtime/mod.rs:482:46
[10911](https://github.com/MystenLabs/sui/runs/8080583027?check_suite_focus=true#step:5:10912)
  37: checkpoints_tests::end_to_end_with_one_byzantine
[10912](https://github.com/MystenLabs/sui/runs/8080583027?check_suite_focus=true#step:5:10913)
             at ./tests/checkpoints_tests.rs:230:5
[10913](https://github.com/MystenLabs/sui/runs/8080583027?check_suite_focus=true#step:5:10914)
  38: checkpoints_tests::end_to_end_with_one_byzantine::{{closure}}
[10914](https://github.com/MystenLabs/sui/runs/8080583027?check_suite_focus=true#step:5:10915)
             at ./tests/checkpoints_tests.rs:208:7
[10915](https://github.com/MystenLabs/sui/runs/8080583027?check_suite_focus=true#step:5:10916)
  39: core::ops::function::FnOnce::call_once
[10916](https://github.com/MystenLabs/sui/runs/8080583027?check_suite_focus=true#step:5:10917)
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/ops/function.rs:248:5
[10917](https://github.com/MystenLabs/sui/runs/8080583027?check_suite_focus=true#step:5:10918)
  40: core::ops::function::FnOnce::call_once
[10918](https://github.com/MystenLabs/sui/runs/8080583027?check_suite_focus=true#step:5:10919)
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/ops/function.rs:248:5
[10919](https://github.com/MystenLabs/sui/runs/8080583027?check_suite_focus=true#step:5:10920)
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[10920](https://github.com/MystenLabs/sui/runs/8080583027?check_suite_focus=true#step:5:10921)
thread 'end_to_end_with_one_byzantine' panicked at 'assertion failed: cnt <= 20', crates/sui/tests/checkpoints_tests.rs:85:9
[10921](https://github.com/MystenLabs/sui/runs/8080583027?check_suite_focus=true#step:5:10922)
stack backtrace:
[10922](https://github.com/MystenLabs/sui/runs/8080583027?check_suite_focus=true#step:5:10923)
   0: rust_begin_unwind
[10923](https://github.com/MystenLabs/sui/runs/8080583027?check_suite_focus=true#step:5:10924)
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/std/src/panicking.rs:584:5
[10924](https://github.com/MystenLabs/sui/runs/8080583027?check_suite_focus=true#step:5:10925)
   1: core::panicking::panic_fmt
[10925](https://github.com/MystenLabs/sui/runs/8080583027?check_suite_focus=true#step:5:10926)
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:142:14
[10926](https://github.com/MystenLabs/sui/runs/8080583027?check_suite_focus=true#step:5:10927)
   2: core::panicking::panic
[10927](https://github.com/MystenLabs/sui/runs/8080583027?check_suite_focus=true#step:5:10928)
             at /rustc/e092d0b6b43f2de967af0887873151bb1c0b18d3/library/core/src/panicking.rs:48:5
[10928](https://github.com/MystenLabs/sui/runs/8080583027?check_suite_focus=true#step:5:10929)
```

**Comment by patrickkuo** [comment]
https://github.com/MystenLabs/sui/issues/4434

**Comment by velvia** [comment]
Close due to #4434
