### ISSUE TITLE
$ fab demo fails due to worker's keypair loading error

### ISSUE THREAD

**Issue by masatsch** [MystenLabs/sui#5180]
### Description

Hello. 

I found that the command `$ fab local` doesn't work well. When I run this command, I got this output.

```
Parsing logs...
ERROR:root:'NoneType' object has no attribute 'group'
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/usr/local/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/Users/masatotsutsumi/workspace/masatsch/narwhal/benchmark/benchmark/logs.py", line 288, in _parse_primaries
    port = search(
AttributeError: 'NoneType' object has no attribute 'group'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/masatotsutsumi/workspace/masatsch/narwhal/benchmark/benchmark/logs.py", line 281, in __init__
    results = p.map(self._parse_primaries, primaries)
  File "/usr/local/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/local/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
AttributeError: 'NoneType' object has no attribute 'group'

ERROR: Failed to run demo

Caused by:
  0: <class 'benchmark.logs.ParseError'>
  1: Failed to parse nodes' logs: 'NoneType' object has no attribute 'group'
```

on the `worker-0-0.log` file

```
Error: Failed to load the node's worker keypair

Caused by:
    Failed to read config file '.worker-0-key.json': signature error at line 3 column 140

Location:
    node/src/main.rs:118:18
```

From the error message, I guessed that the type of key being read was wrong.

When I went to look the Rust codes, I found that the worker KeyPair reads a type called NetworkKayPair.

crypto/src/lib.rs
```rust
pub type NetworkKeyPair = ed25519::Ed25519KeyPair;
```

In contrast, we found that `benchmark/benchmark/full_demo.py`'s implementation generates worker key files with a simple KeyPair type.

```python
            worker_keys = []
            worker_key_files = [PathMaker.worker_key_file(
                i) for i in range(self.workers*nodes)]
            for filename in worker_key_files:
                cmd = CommandMaker.generate_key(filename).split()
                subprocess.run(cmd, check=True)
                worker_keys += [Key.from_file(filename)]
            worker_names = [x.name for x in worker_keys]
```

I changed `generate_key()` to `generate_network_key()` in the above code and it works fine.

### Steps to reproduce

```
$ cd benchmark
$ fab demo
```

**Comment by mwtian** [comment]
Hi @masatsch, thanks for reporting the issue! We recently merged a few fixes to the benchmark. Can you try again to see if the issue still exists?

**Comment by mwtian** [comment]
I believe this is fixed now! Feel free to reopen if the issue still exists.
