### ISSUE TITLE
thread 'main' panicked at 'Sui System State object deserialization cannot fail: Eof'

### ISSUE THREAD

**Issue by ASLanin** [MystenLabs/sui#5425]
## Steps to Reproduce Issue

1. download configs from:
https://github.com/MystenLabs/sui/raw/main/crates/sui-config/data/fullnode-template.yaml
https://github.com/MystenLabs/sui-genesis/raw/main/devnet/genesis.blob

2. use `docker-compose.yaml` from the https://github.com/MystenLabs/sui-genesis/raw/main/devnet/genesis.blob

3. start container by `docker compose up -d`

## Expected Result
container start successfully

## Actual Result
Error:
```
....
fullnode  | 2022-10-20T18:13:38.463694Z  INFO sui_storage::event_store::sql: Recovered last sequence number from event store last_seq_num=0
fullnode  | thread 'main' panicked at 'Sui System State object deserialization cannot fail: Eof', /sui/crates/sui-core/src/authority/authority_store.rs:1382:14
fullnode  | stack backtrace:
fullnode  | 2022-10-20T18:13:38.480878Z ERROR telemetry_subscribers: panicked at 'Sui System State object deserialization cannot fail: Eof', /sui/crates/sui-core/src/authority/authority_store.rs:1382:14 panic.file="/sui/crates/sui-core/src/authority/authority_store.rs" panic.line=1382 panic.column=14
fullnode  |    0:     0x55e06e2779bd - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2b42ca28d244e5c7
fullnode  |    1:     0x55e06e2a078c - core::fmt::write::h401e827d053130ed
fullnode  |    2:     0x55e06e270701 - std::io::Write::write_fmt::hffec93268f5cde32
fullnode  |    3:     0x55e06e279435 - std::panicking::default_hook::{{closure}}::h1f023310983bc730
fullnode  |    4:     0x55e06e279151 - std::panicking::default_hook::h188fec3334afd5be
fullnode  |    5:     0x55e06cb039b6 - telemetry_subscribers::set_panic_hook::{{closure}}::he5852eb7725a0cd1
fullnode  |    6:     0x55e06e279a7a - std::panicking::rust_panic_with_hook::hf26e9d4f97b40096
fullnode  |    7:     0x55e06e2798b7 - std::panicking::begin_panic_handler::{{closure}}::hfab912107608087a
fullnode  |    8:     0x55e06e277eb4 - std::sys_common::backtrace::__rust_end_short_backtrace::h434b685ce8d9965b
fullnode  |    9:     0x55e06e2795e9 - rust_begin_unwind
fullnode  |   10:     0x55e06b9876c3 - core::panicking::panic_fmt::ha6dc7f2ab2479463
fullnode  |   11:     0x55e06b987813 - core::result::unwrap_failed::h42ad8e915aa0a906
fullnode  |   12:     0x55e06bc33083 - sui_core::authority::authority_store::SuiDataStore<S>::get_sui_system_state_object::h9cf071193a11b213
fullnode  |   13:     0x55e06bed0e06 - sui_node::SuiNode::start::{{closure}}::h4950c5a67e0c1aed
fullnode  |   14:     0x55e06bf1e603 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h6af338de7ad624e2
fullnode  |   15:     0x55e06bc37a9f - <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll::h832f69ca2a3b36f9
fullnode  |   16:     0x55e06bace94d - std::thread::local::LocalKey<T>::with::h5158d9d7e27b382a
fullnode  |   17:     0x55e06bd127ff - tokio::park::thread::CachedParkThread::block_on::h4ea2eaa1af06774a
fullnode  |   18:     0x55e06bb216e4 - tokio::runtime::scheduler::multi_thread::MultiThread::block_on::hac6ed422dba14533
fullnode  |   19:     0x55e06bc2290b - tokio::runtime::Runtime::block_on::hb50a3bec1e09b166
fullnode  |   20:     0x55e06bd392a9 - sui_node::main::h06f0469f12f67b35
fullnode  |   21:     0x55e06ba393b3 - std::sys_common::backtrace::__rust_begin_short_backtrace::h1d428248447d565d
fullnode  |   22:     0x55e06bda7f89 - std::rt::lang_start::{{closure}}::hd5e38e51957905a5
fullnode  |   23:     0x55e06e268a4e - std::rt::lang_start_internal::h6612c8a7a6861b8b
fullnode  |   24:     0x55e06bd39398 - main
fullnode  |   25:     0x7fb6db5f6d0a - __libc_start_main
fullnode  |   26:     0x55e06b9a94aa - _start
fullnode  |   27:                0x0 - <unknown>
fullnode  | 2022-10-20T18:13:38.498993Z  INFO sui_storage::lock_service: LockService command loop stopped, the sender on other end hung up/dropped
fullnode  | 2022-10-20T18:13:38.499186Z  INFO sui_storage::lock_service: LockService queries loop stopped, the sender on other end hung up/dropped
fullnode exited with code 101
```

## System Information
>uname -a
Linux sui 5.15.0-25-generic #25-Ubuntu SMP Wed Mar 30 15:54:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

>lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy

>docker version
Client: Docker Engine - Community
 Version:           20.10.20
 API version:       1.41
 Go version:        go1.18.7
 Git commit:        9fdeb9c
 Built:             Tue Oct 18 18:20:18 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.20
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.18.7
  Git commit:       03df974
  Built:            Tue Oct 18 18:18:08 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.8
  GitCommit:        9cd3357b7fd7218e4aec3eae239db1f68a5a6ec6
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by ASLanin** [comment]
Temporary problem with  the bad [genesis.blob](https://github.com/MystenLabs/sui-genesis/raw/main/devnet/genesis.blob)
Solved.
