### ISSUE TITLE
TS SDK: Publishing a package returns RPC Error

### ISSUE THREAD

**Issue by ThounyBreasty** [MystenLabs/sui#7380]
## Steps to Reproduce Issue

Use the example from README "To publish a package".

```typescript
import { Ed25519Keypair, JsonRpcProvider, RawSigner } from '@mysten/sui.js';
const { execSync } = require('child_process');
// Generate a new Keypair
const keypair = new Ed25519Keypair();
// or with 
// const keypair = Ed25519Keypair.deriveKeypair("mnemonic here")
const provider = new JsonRpcProvider();
const signer = new RawSigner(keypair, provider);
const compiledModules = JSON.parse(
  execSync(
    `${cliPath} move build --dump-bytecode-as-base64 --path ${packagePath}`,
    { encoding: 'utf-8' }
  )
);
const modulesInBytes = compiledModules.map((m) =>
  Array.from(new Base64DataBuffer(m).getData())
);
const publishTxn = await signer.publish({
  compiledModules: modulesInBytes,
  gasBudget: 10000,
});
console.log('publishTxn', publishTxn);
```

## Expected Result

Expected to get the package publish and log the publishTxn

## Actual Result

```
Error: RPC Error: invalid type: sequence, expected a string at line 1 column 1
    at RpcTxnDataSerializer.serializeToBytes (/home/project/snippets/node_modules/.pnpm/@mysten+sui.js@0.22.0/node_modules/@mysten/sui.js/src/signers/txn-data-serializers/rpc-txn-data-serializer.ts:171:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RawSigner.signAndExecuteTransaction (/home/project/snippets/node_modules/.pnpm/@mysten+sui.js@0.22.0/node_modules/@mysten/sui.js/src/signers/signer-with-provider.ts:132:7)
    at async /home/project/snippets/src/index.ts:31:24
 ELIFECYCLE  Command failed with exit code 1.
```

The error is thrown line 31 which is 
```typescript
const publishTxn = await signer.publish({
  compiledModules: modulesInBytes,
  gasBudget: 10000,
});
```

I logged `modulesInBytes` and `compiledModules` and it looks correct.

## System Information

* OS: PopOs (Debian)
* sui: 0.21.0
* Move.toml: 0.21.0

**Comment by Eis-D-Z** [comment]
I see this, it won't work anyways since the newly created address won't have SUI for gas. Will look into this.
In the meantime I suggest to try directly the `sui client publish` tool

**Comment by Eis-D-Z** [comment]
The only fault with this is the:
```
const modulesInBytes = compiledModules.map((m) =>
  Array.from(new Base64DataBuffer(m).getData())
);
```
If you remove this part and pass `compiledModules` directly to the `signer.publish({compiledModules: compiledModules...`
it will work. The docs will be updated soon.

**Comment by ThounyBreasty** [comment]
I tried with a funded account as well, hence the `mnemonic here` comment.

By the way, I also tried by passing `compiledModules` instead of `modulesInBytes` with `signer.publish` (I saw this somewhere on github) but I get another error:

```
/home/project/snippets/node_modules/.pnpm/@mysten+sui.js@0.22.0/node_modules/@mysten/sui.js/src/providers/json-rpc-provider.ts:621
      throw new Error(`Error executing transaction with request type: ${err}`);
            ^
Error: Error executing transaction with request type: Error: RPC Error: Transaction timed out before reaching finality
    at JsonRpcProvider.executeTransaction (/home/project/snippets/node_modules/.pnpm/@mysten+sui.js@0.22.0/node_modules/@mysten/sui.js/src/providers/json-rpc-provider.ts:621:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RawSigner.signAndExecuteTransaction (/home/project/snippets/node_modules/.pnpm/@mysten+sui.js@0.22.0/node_modules/@mysten/sui.js/src/signers/signer-with-provider.ts:123:14)
    at async RawSigner.signAndExecuteTransaction (/home/project/snippets/node_modules/.pnpm/@mysten+sui.js@0.22.0/node_modules/@mysten/sui.js/src/signers/signer-with-provider.ts:131:12)
    at async /home/project/snippets/src/index.ts:31:24
 ELIFECYCLE  Command failed with exit code 1.
```
