### ISSUE TITLE
panicked at 'We should have the whole history by now'

### ISSUE THREAD

**Issue by mystenmark** [MystenLabs/sui#7537]
Hit this panic when testing load with reconfiguration + node restarts. To repro, check out branch `mlogan-node-restarts`, (commit `4fb871ba1`) and run:

```
cd crates/sui-benchmark
RUST_BACKTRACE=1 CHECKPOINTS_PER_EPOCH=10 SIM_STRESS_TEST_DURATION_SECS=300 USE_MOCK_CRYPTO=1 MSIM_TEST_SEED=2 RUST_LOG=error cargo simtest --test simtest test_simulated_load --no-capture
```

Stack trace is:

```
thread '<unnamed>' panicked at 'We should have the whole history by now', narwhal/consensus/src/utils.rs:48:14
stack backtrace:
   0: rust_begin_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   2: core::panicking::panic_display
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:72:5
   3: core::panicking::panic_str
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:56:5
   4: core::option::expect_failed
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/option.rs:1880:5
   5: core::option::Option<T>::expect
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/option.rs:738:21
   6: narwhal_consensus::utils::linked
             at /Users/mlogan/dev/sui/narwhal/consensus/src/utils.rs:46:19
   7: narwhal_consensus::utils::order_leaders
             at /Users/mlogan/dev/sui/narwhal/consensus/src/utils.rs:34:12
   8: <narwhal_consensus::bullshark::Bullshark as narwhal_consensus::consensus::ConsensusProtocol>::process_certificate
             at /Users/mlogan/dev/sui/narwhal/consensus/src/bullshark.rs:147:23
   9: narwhal_consensus::consensus::Consensus<Protocol>::run_inner::{{closure}}
             at /Users/mlogan/dev/sui/narwhal/consensus/src/consensus.rs:335:25
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/future/mod.rs:91:19
  11: narwhal_consensus::consensus::Consensus<Protocol>::run::{{closure}}
             at /Users/mlogan/dev/sui/narwhal/consensus/src/consensus.rs:301:31
```

**Comment by mztacat** [comment]
same i checked it too
