### ISSUE TITLE
assertion failure in transaction manager

### ISSUE THREAD

**Issue by mystenmark** [MystenLabs/sui#7997]
happens sometime around https://github.com/MystenLabs/sui/tree/6fa859ba7590deb6db72aad42ca689efd69d5329

```
2023-02-01T18:14:37.781102Z ERROR telemetry_subscribers: panicked at 'assertion failed: inner.executing_certificates.insert(digest)', crates/sui-core/src/transaction_manager.rs:190:17 panic.file="crates/sui-core/src/transaction_manager.rs" panic.line=190 panic.column=17
thread 'tokio-runtime-worker' panicked at 'assertion failed: inner.executing_certificates.insert(digest)', crates/sui-core/src/transaction_manager.rs:190:17
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: sui_core::transaction_manager::TransactionManager::enqueue
   4: <sui_core::consensus_handler::ConsensusHandler<T> as narwhal_executor::ExecutionState>::handle_consensus_output::{{closure}}::{{closure}}
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   8: tokio::runtime::task::core::Core<T,S>::poll
   9: tokio::runtime::task::harness::Harness<T,S>::poll
  10: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  11: tokio::runtime::scheduler::multi_thread::worker::Context::run
  12: tokio::runtime::scheduler::multi_thread::worker::run
  13: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
  14: tokio::runtime::task::core::Core<T,S>::poll
  15: tokio::runtime::task::harness::Harness<T,S>::poll
  16: tokio::runtime::blocking::pool::Inner::run
```

**Comment by mwtian** [comment]
Pushed f23377f17f48455c85ea8128f60b9ceaf7b3d4a4 to `testnet` branch.
