### ISSUE TITLE
[Local Faucet Error] panicked at 'mpsc bounded channel requires buffer > 0'

### ISSUE THREAD

**Issue by 99Kies** [MystenLabs/sui#8078]
How to start the tap service locally, I have started the local node.
my local node:
```
sui genesis
sui start
```

this is my command:
```
./sui-faucet --write-ahead-log no.log --amount 10000000000000
```

this is my log:
```
2023-02-03T19:11:59.992209Z  INFO sui_faucet: Max concurrency: 30.
2023-02-03T19:11:59.993494Z  INFO sui_faucet: Initialize wallet from config path: "/Users/feng/.sui/sui_config/client.yaml"
2023-02-03T19:11:59.996729Z  INFO sui_faucet: Starting Prometheus HTTP endpoint at 0.0.0.0:9184
2023-02-03T19:11:59.999209Z  INFO sui_faucet::faucet::simple_faucet: SimpleFaucet::new with active address: 0x22d10a88732125025b38af6715aab4cbf49b6720
thread '2023-02-03T19:12:00.014914Z ERROR telemetry_subscribers: panicked at 'mpsc bounded channel requires buffer > 0', /Users/feng/Desktop/sui-move/sui/crates/sui-faucet/src/faucet/simple_faucet.rs:86:36 panic.file="/Users/feng/Desktop/sui-move/sui/crates/sui-faucet/src/faucet/simple_faucet.rs" panic.line=86 panic.column=36
main' panicked at 'mpsc bounded channel requires buffer > 0', /Users/feng/Desktop/sui-move/sui/crates/sui-faucet/src/faucet/simple_faucet.rs:86:36
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[1]    79003 abort      ./sui-faucet --write-ahead-log no.log --amount 10000000000000
```

**Comment by 99Kies** [comment]
use this command:
```
# start localnet(rpc: 9000) and faucet(9123)
sui-test-validator

# get faucet
curl -H "Content-Type: application/json" \
     -X POST \
     -d '{"recipient":"<Account Address>"}' \
     "http://127.0.0.1:9123/faucet"
```

**Comment by 99Kies** [comment]
That doesn't work either.

**Comment by stefan-mysten** [comment]
When starting a node via `sui-test-validator`, the correct cURL command is: 
```shell
curl --location --request POST 'http://127.0.0.1:9123/gas' \
--header 'Content-Type: application/json' \
--data-raw '{
    "FixedAmountRequest": {
        "recipient": "YOUR_ADDRESS_HERE"
    }
}'
```
