### ISSUE TITLE
executeMoveCall 504

### ISSUE THREAD

**Issue by taerbao** [MystenLabs/sui#9575]
```
Error: Error executing transaction with request type: Error: 504 Gateway Time-out
    at JsonRpcProvider.<anonymous> (file:///Users/admin/maker/sui/sui-test/node_modules/@mysten/sui.js/dist/index.mjs:3778:15)
    at Generator.throw (<anonymous>)
    at rejected (file:///Users/admin/maker/sui/sui-test/node_modules/@mysten/sui.js/dist/index.mjs:52:29)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
``` 

```
const moveCallTxn = await signer.executeMoveCall({
        packageObjectId: '0x2',
        module: 'devnet_nft',
        function: 'mint',
        typeArguments: [],
        arguments: [
            'Example NFT By Guozi-1',
            'An NFT created by GUozi',
            'ipfs://bafkreibngqhl3gaa7daob4i2vccziay2jjlp435cf66vhono7nrvww53ty',
        ],
        gasBudget: 20000,
    });
    console.log('moveCallTxn', moveCallTxn);
```

**Comment by stefan-mysten** [comment]
This was likely a network issue which has probably been resolved since March. Closing the issue for now but feel free @taerbao to create a fresh issue if you encounter any problems.
