### ISSUE TITLE
[ts-sdk][bug] Object array arguments are not supported

### ISSUE THREAD

**Issue by LeviHHH** [MystenLabs/sui#9991]
# Description
For move code below, the tssdk can not build such tranaction:
```rust
public entry fun deposits<T>(coins: vector<Coin<T>>) {
}
```
Error:
```shell
Error: Unknown call arg type {
  "Vector": {
    "Struct": {
      "address": "0x2",
      "module": "coin",
      "name": "Coin",
      "typeArguments": [
        {
          "TypeParameter": 0
        }
      ]
    }
  }
} for value [
  "0xf76d0126e2f18953220372f8593c37ad9297005b03657369733899a7b35300a9"
]
    at /Users/PROJECT/node_modules/@mysten/sui.js/src/builder/Transaction.ts:558:19
    at Array.forEach (<anonymous>)
    at /Users/PROJECT/node_modules/@mysten/sui.js/src/builder/Transaction.ts:520:18
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async _Transaction.prepare_fn (/Users/PROJECT/node_modules/@mysten/sui.js/src/builder/Transaction.ts:492:7)
    at async _Transaction.build (/Users/PROJECT/node_modules/@mysten/sui.js/src/builder/Transaction.ts:346:5)
    at async RawSigner.signTransaction (/Users/PROJECT/node_modules/@mysten/sui.js/src/signers/signer-with-provider.ts:91:26)
    at async RawSigner.signAndExecuteTransaction (/Users/PROJECT/node_modules/@mysten/sui.js/src/signers/signer-with-provider.ts:129:45)
    at async MavenContract.call (/Users/PROJECT/scripts/lib/contract.ts:20:16)
```
tssdk version: `0.0.0-experimental-20230324011546`

example tscode:
```typescript
async function call(method: string, callArguments: any[] = [], typeArguments: string[] = []) {
    const tx = new Transaction();
    tx.moveCall({
        target: `${this.address}::${this.module}::${method}`,
        arguments: callArguments.map(arg => tx.pure(arg)),
        typeArguments
    });
    tx.setGasBudget(100000);
    return await this.signer.signAndExecuteTransaction({
        transaction: tx, requestType: 'WaitForLocalExecution', options: {
            showInput: true,
            showEffects: true,
            showEvents: true,
            showObjectChanges: true,
            showBalanceChanges: true,
        }
    });
}
const coinObjectID = '0xf76d0126e2f18953220372f8593c37ad9297005b03657369733899a7b35300a9';
await call('deposits', [coinObjectID], [SuiCoin]);
```

**Comment by LeviHHH** [comment]
@Jordan-Mysten Could you take a look at it?

**Comment by devlb1024** [comment]
![k8fF7RgEKC](https://user-images.githubusercontent.com/101561247/228244281-3019ddec-c31b-4df9-9aed-b071c0573106.jpg)
I have the same problem, I don't know if it is sdk bug

**Comment by tnowacki** [comment]
You will need to use `makeMoveVec` in order to generate the vector of objects. For pure non-object values, it should still work.

**Comment by LeviHHH** [comment]
> You will need to use `makeMoveVec` in order to generate the vector of objects. For pure non-object values, it should still work.
> 
> As a side note, You should rewrite anything like
> 
> ```
> public entry fun deposits<T>(coins: vector<Coin<T>>) {
> ```
> 
> to
> 
> ```
> public entry fun deposit<T>(coins: Coin<T>) {
> ```
> 
> Since you can use `mergeCoins` to merge the coins before calling the function.
Can we make the `pure` function support vector of objects? This will make the sdk easier to use.

**Comment by tnowacki** [comment]
`pure` is used for non-object arguments. 
But we could maybe detect an vector of objects and auto-insert a `makeMoveVec` call.
